# Generated by Django 4.1.6 on 2023-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_upvotes_userroomvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
