# Generated by Django 4.1.6 on 2023-03-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_downvoted_by_room_upvoted_by_alter_room_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='downvotes',
        ),
    ]
