# Generated by Django 4.1.6 on 2023-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_room_downvoted_by_remove_room_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
