# Generated by Django 4.1.6 on 2023-03-27 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_room_access_code_room_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
