# Generated by Django 4.1.6 on 2023-04-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
